### ISSUE TITLE
Logging fails if the caller does not supply all additional fields

### ISSUE THREAD

**Issue by claudio-silva** [waza-ari/monolog-mysql#10]
If I define an additional field A, I can no longer issue a call like:
```php
$logger->log($msg);
```
It will fail with `SQLSTATE[HY093]: Invalid parameter number`
I would have to **always** pass an extra array on all logging calls, like this:
```php
$logger->log($msg, ['A'=>'something']);
```
Not all logging calls in an application can be made to always supply all the extra fields, sometimes that is not even under the control of the application developer (a third-party library may be making it's own logging calls, for instance).

**Comment by claudio-silva** [comment]
You can solve this by adding the following code at line 130 of MySQLHandler.php:
```php
$contentArray = $contentArray + array_combine (
    $this->additionalFields, array_fill (0, count ($this->additionalFields), null)
  );
```

**Comment by mattvb91** [comment]
Having the same issue when I define no extra columns:

    Invalid parameter number

If I have only the default columns: channel, level, message, time it will do an array_merge on line 120 and add $record['context'] which results in the invalid parameter number.

**Comment by borys-p** [comment]
Is this project still alive?

**Comment by waza-ari** [comment]
It is alive, yes. Well... at least I am :)  Going to look at this tomorrow, sorry for the very long delay

**Comment by waza-ari** [comment]
Could you please test latest master commit whether it fixes the problem?

**Comment by claudio-silva** [comment]
Thank you, @waza-ari
