### ISSUE TITLE
Declaration of MySQLHandler\MySQLHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void

### ISSUE THREAD

**Issue by pinyht** [waza-ari/monolog-mysql#32]
Declaration of MySQLHandler\MySQLHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void

can't use with monolog v2.0.0

**Comment by michalzimniak** [comment]
Declaration of MySQLHandler\\MySQLHandler::write(array $record) must be compatible with Monolog\\Handler\\AbstractProcessingHandler::write(array $record): void in MySQLHandler.php on line 17

**Comment by cherryred5959** [comment]
I'm trying to figure out the changes to the Monolog in my spare time, please wait!

**Comment by czachor** [comment]
Any chance of merging @kovenant's fix?

**Comment by nooborka** [comment]
Any chance of merging @kovenant's fix?

**Comment by amacado** [comment]
A patch of this error will be available in https://github.com/waza-ari/monolog-mysql/pull/47
