### ISSUE TITLE
Include Level name

### ISSUE THREAD

**Issue by TwinMist** [waza-ari/monolog-mysql#34]
Hi 
is it possible to include the level name and write this into the database automaticly?
array(8) {
  ["DEBUG"]=>
  int(100)
  ["INFO"]=>
  int(200)
  ["NOTICE"]=>
  int(250)
  ["WARNING"]=>
  int(300)
  ["ERROR"]=>
  int(400)
  ["CRITICAL"]=>
  int(500)
  ["ALERT"]=>
  int(550)
  ["EMERGENCY"]=>
  int(600)
}
thanks

**Comment by amacado** [comment]
Hello @TwinMist I don't see the advantage of having the level as string. You can always compare and select to the levels as enums. Also numeric storage allows to sort rows with ease. Feel free to re-open the request with an explanation why you think having the strings in the database is an advantage over the current implementation.
