### ISSUE TITLE
errors in handler

### ISSUE THREAD

**Issue by StephanKrauss** [waza-ari/monolog-mysql#37]
Hello,

i will use the monolog-mysql to write messages in the 'logs' table.
With composer i have installed the last version of monolog-mysql.
The version is 1.0.4 .

1.
When i start the first time, i get an error.
In the class 'MySQLHandler' -> write() need ' : void'

2.
I will send same information with Monolog.
Here my test skript
--------------------
try{
// MySQL Logger
    $dsn = 'mysql:dbname=test;host=localhost';
    $user = 'test';
    $password = 'test';

    $pdo = new \PDO($dsn, $user, $password);

   $mySQLHandler = new MySQLHandler($pdo, "logs", array('errorCode', 'line', 'file'), \Monolog\Logger::DEBUG);
    $logger_mysql = new Logger('MyApp2');
    $logger_mysql->pushHandler($mySQLHandler);

    throw new \Exception('ein Fehler', 1005);
}
catch(\Throwable $e){
    $info = [
        'errorCode' => $e->getCode(),
        'line' => $e->getLine(),
        'file' => $e->getFile()
    ];

    $logger_mysql->alert($e->getMessage(), $info);
}
--------------------

In the database exists a 'logs' table.
After a test the table has the columns 'id' , 'errorCode' , 'line' and 'file' .
I missing the standard columns of Monolog.

In the method write is the line:

$this->statement->execute($contentArray);

This executed the query:
INSERT INTO `logs` (channel, level, message, time, errorCode, line, file) VALUES (:channel, :level, :message, :time, :errorCode, :line, :file)

But nothing happened.

Can you help ?

Your sincerly

Stephan

**Comment by amacado** [comment]
Hello @StephanKrauss, since this issue is from 2019 I assume you've found a solution or the question is no longer relevant. I'll close it in terms of housekeeping.
