### ISSUE TITLE
information to logs table

### ISSUE THREAD

**Issue by StephanKrauss** [waza-ari/monolog-mysql#38]
Hello,

if i correct the columns of the table manually,
the application works.

Is there a way to the value of time in the ISO8601 standard.
Is better ro read.

Your sincerly

Stephan

**Comment by ChrisToxz** [comment]
https://github.com/waza-ari/monolog-mysql/pull/40

**Comment by amacado** [comment]
Hello @StephanKrauss, in the next release (https://github.com/waza-ari/monolog-mysql/pull/47) I'll adopt the request of having a dedicated `datetime `column.
