### ISSUE TITLE
question regarding capabilities

### ISSUE THREAD

**Issue by cordoval** [waza-ari/monolog-mysql#4]
i am looking to obfuscate specifically an error on Mysql and so that when logged it does not leak any values persisted to the database, just the shape or form of the tables and fields but never values.

I believe we can extend this to do just that.

**Comment by waza-ari** [comment]
Hm - could you elaborate a little more? I currently do not get the point. 

You have an application that logs to MySQL, but you want certain log types (or specific entries) not to log actual values but obfuscated data?

If this is true, maybe a custom hook/callback function before actually inserting the log which can modify the log entry may do the job?

**Comment by cordoval** [comment]
i did a processor if that is what you mean and it works well. However I was looking for something more less intrusive but i think i am good with what i have done. For a second thought it could live in a library to be shared.

**Comment by waza-ari** [comment]
Yeah, processor was the word I was looking for. I believe it should not be the responsibility of the actual handler to modify log entries. Monolog provides a convenient way to so using the available processors or the possibility to create own.

I thing this is the way to go, what you obviously already did.
