### ISSUE TITLE
PDOStatement::execute(): SQLSTATE[HY093]

### ISSUE THREAD

**Issue by TwinMist** [waza-ari/monolog-mysql#41]
Hi
Just had to revert back to 1.0.4 because in 1.0.5 was getting
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in 

any ideas

**Comment by StephanKrauss** [comment]
Hello,

i have the same problem.
Here is my test setup
--------------------------------
$pdo = new \PDO('mysql:host=localhost;dbname=monolog', 'monolog', 'monolog');

            $mysqlHandler = new \MySQLHandler\MySQLHandler($pdo, "log", array('channel', 'HD_CORRELATION_ID', 'errorFile', 'errorFile', 'errorLine', 'errorTrace'), \Monolog\Logger::INFO);

            $this->logger->pushHandler($mysqlHandler);

            $content = [
                'test1' => 'aaa',
                'test2' => 'bbb'
            ];

            $this->logger->error('Test', $content);
---------------------------

When i debug hte script i find the query for mysql.
Query: INSERT INTO `log` (channel, level, message, time, channel, HD_CORRELATION_ID, errorFile, errorFile, errorLine, errorTrace) VALUES (:channel, :level, :message, :time, :channel, :HD_CORRELATION_ID, :errorFile, :errorFile, :errorLine, :errorTrace)

What is wrong ?

Your sincerly

Stephan

**Comment by cherryred5959** [comment]
@TwinMist @StephanKrauss   I think I'll have time to check this out next week, please wait a little while.

**Comment by Noone-404** [comment]
Reverting commit 45a4bf3168c21b13272d16651f073a62bffd3cb0 fixes this for me.

For once, the check for unused keys is using a wrong array index:
https://github.com/waza-ari/monolog-mysql/blob/45a4bf3168c21b13272d16651f073a62bffd3cb0/src/MySQLHandler/MySQLHandler.php#L210
This should probably be `if(! isset($contentArray[$context]))`.

But the check does not seem to work correctly anyway as the insert statement is build and prepared prior to the unused keys getting removed. Thus, the statement always contains _all_ additional fields/keys.

By (trying to) remove them after the statement has already been prepared, the parameters won't match up.

**Comment by amacado** [comment]
I've addressed this issue in https://github.com/waza-ari/monolog-mysql/pull/47/commits/4eb4ad35a16ecf5e16701326fb6a419bedee4552. It will be resolved in the upcomming release v2.
