### ISSUE TITLE
PHP 5 Support

### ISSUE THREAD

**Issue by garbinmarcelo** [waza-ari/monolog-mysql#44]
Hello how are you? 

Does this extension work with PHP 5? 

Thanks

**Comment by waza-ari** [comment]
This project is more or less unmaintained, you'll probably need to figure out on your own. 

As PHP 5 is unmaintained and EOL since January 2019, I doubt anyone will put effort in it if it doesn't work. Also Monolog 2.x and 3.x do not support PHP5.

**Comment by garbinmarcelo** [comment]
Ok, maybe if I really use it I'll fork and rewrite it to PHP 5. Today we have a legacy system that makes it unfeasible to update the PHP version at the moment, but we need this issue of Logs.

Thank you for your feedback and attention.

**Comment by waza-ari** [comment]
Just give it a try, it may work out of the box. When I started writing it I used PHP5, and unless someone made a breaking change it might still work. Good luck!
