### ISSUE TITLE
Write 'extra' passed by Processors to db

### ISSUE THREAD

**Issue by ghost** [waza-ari/monolog-mysql#6]
Default monolog processors pass their info in `$record['extra']` not only `$record['context']`.

If you want them to be written to db to, merging them into context before write could be a way to go.

**Comment by waza-ari** [comment]
Sorry I did not had the time to look at your pull request yet. I will check it tomorrow and get back to you. Thanks for contributing!

**Comment by waza-ari** [comment]
Merged. Thanks.
